FROM python:3.9-alpine3.16

COPY requirements.txt /temp/requirements.txt

RUN apk add --no-cache postgresql-client build-base postgresql-dev python3-dev
RUN pip install -r /temp/requirements.txt

WORKDIR /service

COPY telegram_bot /service/telegram_bot/

RUN adduser --disabled-password bot-user
USER bot-user

CMD ["python", "telegram_bot/bot.py"]