# Generated by Django 3.2.25 on 2026-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20260202_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
