# Generated by Django 3.2.16 on 2026-01-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=160)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
